server:
  port: 8080
# Enabling H2 Console
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: user-service

  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true
    hibernate:
      ddl-auto: none